# Generated by Django 3.2.5 on 2022-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='회원번호')),
                ('user_id', models.CharField(max_length=30, verbose_name='아이디')),
                ('pw', models.CharField(max_length=20, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'user',
            },
        ),
    ]
